In [1]:
import requests
import pandas as pd
import simplejson as json

In [2]:
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={}&apikey=Y1BD47K4VT0VB7BK.'
req = requests.get(url).json()

In [2]:
def fetch_response(symbol,apikey,url):
    url = url + '&symbol={}&apikey={}'.format(symbol, apikey)
    return requests.get(url).json()

In [3]:
req = fetch_response('UAL', 'Y1BD47K4VT0VB7BK', 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY' )

In [4]:
def fetch_response(symbol):
    url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY' + '&symbol={}&apikey=Y1BD47K4VT0VB7BK'.format(symbol)
    return requests.get(url).json()

In [5]:
req = fetch_response('UAL' )

In [6]:
req

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'UAL',
  '3. Last Refreshed': '2021-04-16',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2021-04-16': {'1. open': '56.4700',
   '2. high': '57.1500',
   '3. low': '55.7100',
   '4. close': '55.8700',
   '5. volume': '10620386'},
  '2021-04-15': {'1. open': '57.7900',
   '2. high': '57.8514',
   '3. low': '55.5700',
   '4. close': '56.1200',
   '5. volume': '12123396'},
  '2021-04-14': {'1. open': '57.4600',
   '2. high': '58.5200',
   '3. low': '56.5400',
   '4. close': '56.9200',
   '5. volume': '12971146'},
  '2021-04-13': {'1. open': '54.4060',
   '2. high': '56.8600',
   '3. low': '53.9000',
   '4. close': '56.6600',
   '5. volume': '15349381'},
  '2021-04-12': {'1. open': '57.5700',
   '2. high': '57.7100',
   '3. low': '55.2900',
   '4. close': '56.1600',
   '5. volume': '18714698'},
  '2021-04-09': {'1. open': '59.0200',
   '2. high': '59.3601',
   '3. low': '57.7850',
   '4. close': '58.4300',
   '5. volume': '10896080'},
  '2021-04-08': {'1. open': '59.1400',
   '2. high': '59.4700',
   '3. low': '57.7500',
   '4. close': '59.4300',
   '5. volume': '13655758'},
  '2021-04-07': {'1. open': '59.7900',
   '2. high': '61.3399',
   '3. low': '59.1900',
   '4. close': '59.5700',
   '5. volume': '13772591'},
  '2021-04-06': {'1. open': '59.8780',
   '2. high': '60.4200',
   '3. low': '58.8700',
   '4. close': '59.4800',
   '5. volume': '11917227'},
  '2021-04-05': {'1. open': '59.3400',
   '2. high': '60.8900',
   '3. low': '58.9400',
   '4. close': '59.2900',
   '5. volume': '17175712'},
  '2021-04-01': {'1. open': '57.6619',
   '2. high': '58.5450',
   '3. low': '57.2800',
   '4. close': '57.8200',
   '5. volume': '10932226'},
  '2021-03-31': {'1. open': '58.0000',
   '2. high': '58.0115',
   '3. low': '57.0600',
   '4. close': '57.5400',
   '5. volume': '11023782'},
  '2021-03-30': {'1. open': '56.7800',
   '2. high': '58.5000',
   '3. low': '56.4800',
   '4. close': '58.2100',
   '5. volume': '12708910'},
  '2021-03-29': {'1. open': '56.8000',
   '2. high': '57.3100',
   '3. low': '55.4100',
   '4. close': '56.2000',
   '5. volume': '12083040'},
  '2021-03-26': {'1. open': '57.0900',
   '2. high': '57.3700',
   '3. low': '55.2200',
   '4. close': '56.8300',
   '5. volume': '15432445'},
  '2021-03-25': {'1. open': '52.9050',
   '2. high': '56.2900',
   '3. low': '52.0301',
   '4. close': '56.0500',
   '5. volume': '21500079'},
  '2021-03-24': {'1. open': '55.6600',
   '2. high': '56.9600',
   '3. low': '53.7800',
   '4. close': '53.8300',
   '5. volume': '18015776'},
  '2021-03-23': {'1. open': '57.1100',
   '2. high': '58.0800',
   '3. low': '53.8500',
   '4. close': '54.3600',
   '5. volume': '21698204'},
  '2021-03-22': {'1. open': '59.7500',
   '2. high': '60.2000',
   '3. low': '58.2100',
   '4. close': '58.3300',
   '5. volume': '12958276'},
  '2021-03-19': {'1. open': '60.9000',
   '2. high': '60.9500',
   '3. low': '58.6400',
   '4. close': '60.7700',
   '5. volume': '19643819'},
  '2021-03-18': {'1. open': '62.1700',
   '2. high': '63.6999',
   '3. low': '60.5800',
   '4. close': '60.8200',
   '5. volume': '19129709'},
  '2021-03-17': {'1. open': '59.1100',
   '2. high': '62.5600',
   '3. low': '58.8600',
   '4. close': '62.4500',
   '5. volume': '18338038'},
  '2021-03-16': {'1. open': '61.1100',
   '2. high': '61.2000',
   '3. low': '59.2100',
   '4. close': '59.8100',
   '5. volume': '18306413'},
  '2021-03-15': {'1. open': '58.2500',
   '2. high': '61.6900',
   '3. low': '57.9185',
   '4. close': '60.9400',
   '5. volume': '35374512'},
  '2021-03-12': {'1. open': '54.0000',
   '2. high': '56.4400',
   '3. low': '53.6100',
   '4. close': '56.2900',
   '5. volume': '19762477'},
  '2021-03-11': {'1. open': '54.3000',
   '2. high': '55.8700',
   '3. low': '53.3700',
   '4. close': '54.0600',
   '5. volume': '17140757'},
  '2021-03-10': {'1. open': '53.4000',
   '2. high': '54.3700',
   '3. low': '52.8500',
   '4. close': '53.9200',
   '5. volume': '13438932'},
  '2021-03-09': {'1. open': '53.8100',
   '2. high': '54.1550',
   '3. low': '51.8000',
   '4. close': '53.4300',
   '5. volume': '15292842'},
  '2021-03-08': {'1. open': '51.3500',
   '2. high': '54.3325',
   '3. low': '51.3400',
   '4. close': '54.0600',
   '5. volume': '17588966'},
  '2021-03-05': {'1. open': '52.6453',
   '2. high': '52.7300',
   '3. low': '46.5600',
   '4. close': '50.5200',
   '5. volume': '21503158'},
  '2021-03-04': {'1. open': '54.6400',
   '2. high': '54.8500',
   '3. low': '49.9500',
   '4. close': '52.0500',
   '5. volume': '19937491'},
  '2021-03-03': {'1. open': '53.6100',
   '2. high': '55.2000',
   '3. low': '53.2800',
   '4. close': '54.5700',
   '5. volume': '18438946'},
  '2021-03-02': {'1. open': '53.6600',
   '2. high': '54.0500',
   '3. low': '52.7500',
   '4. close': '53.2100',
   '5. volume': '12370989'},
  '2021-03-01': {'1. open': '55.4400',
   '2. high': '55.9300',
   '3. low': '52.7800',
   '4. close': '53.3100',
   '5. volume': '19500588'},
  '2021-02-26': {'1. open': '51.5100',
   '2. high': '53.4100',
   '3. low': '51.2000',
   '4. close': '52.6800',
   '5. volume': '18276380'},
  '2021-02-25': {'1. open': '54.8500',
   '2. high': '55.0000',
   '3. low': '50.4200',
   '4. close': '51.7800',
   '5. volume': '25733579'},
  '2021-02-24': {'1. open': '51.1100',
   '2. high': '55.8700',
   '3. low': '50.8700',
   '4. close': '54.9600',
   '5. volume': '27482084'},
  '2021-02-23': {'1. open': '50.2000',
   '2. high': '51.1823',
   '3. low': '46.9600',
   '4. close': '50.6100',
   '5. volume': '20124969'},
  '2021-02-22': {'1. open': '49.2600',
   '2. high': '51.8200',
   '3. low': '48.3500',
   '4. close': '49.7000',
   '5. volume': '27424508'},
  '2021-02-19': {'1. open': '45.5228',
   '2. high': '48.3600',
   '3. low': '45.4400',
   '4. close': '48.0300',
   '5. volume': '21112041'},
  '2021-02-18': {'1. open': '45.1969',
   '2. high': '45.4400',
   '3. low': '44.3000',
   '4. close': '44.9600',
   '5. volume': '10250399'},
  '2021-02-17': {'1. open': '45.4100',
   '2. high': '46.4800',
   '3. low': '44.7200',
   '4. close': '46.0800',
   '5. volume': '12776642'},
  '2021-02-16': {'1. open': '45.0665',
   '2. high': '45.8100',
   '3. low': '44.5600',
   '4. close': '45.7100',
   '5. volume': '13954879'},
  '2021-02-12': {'1. open': '43.1100',
   '2. high': '44.4710',
   '3. low': '42.9000',
   '4. close': '43.9350',
   '5. volume': '8987489'},
  '2021-02-11': {'1. open': '43.6400',
   '2. high': '43.8400',
   '3. low': '42.9900',
   '4. close': '43.4400',
   '5. volume': '8478124'},
  '2021-02-10': {'1. open': '43.8600',
   '2. high': '44.2199',
   '3. low': '43.3600',
   '4. close': '43.7800',
   '5. volume': '9700292'},
  '2021-02-09': {'1. open': '44.0600',
   '2. high': '44.0915',
   '3. low': '42.8200',
   '4. close': '43.3200',
   '5. volume': '11900771'},
  '2021-02-08': {'1. open': '42.5000',
   '2. high': '44.6400',
   '3. low': '42.2200',
   '4. close': '44.3500',
   '5. volume': '19794297'},
  '2021-02-05': {'1. open': '42.8800',
   '2. high': '42.9400',
   '3. low': '41.9400',
   '4. close': '42.1400',
   '5. volume': '10764265'},
  '2021-02-04': {'1. open': '42.1500',
   '2. high': '42.6100',
   '3. low': '41.8399',
   '4. close': '42.4100',
   '5. volume': '13633792'},
  '2021-02-03': {'1. open': '41.0200',
   '2. high': '42.2000',
   '3. low': '40.5200',
   '4. close': '42.0400',
   '5. volume': '15174840'},
  '2021-02-02': {'1. open': '40.6300',
   '2. high': '40.9050',
   '3. low': '39.9400',
   '4. close': '40.8300',
   '5. volume': '13067720'},
  '2021-02-01': {'1. open': '40.3450',
   '2. high': '40.4100',
   '3. low': '39.1750',
   '4. close': '39.9350',
   '5. volume': '13143423'},
  '2021-01-29': {'1. open': '42.1107',
   '2. high': '42.5000',
   '3. low': '39.7700',
   '4. close': '39.9900',
   '5. volume': '24192571'},
  '2021-01-28': {'1. open': '42.8265',
   '2. high': '44.2000',
   '3. low': '41.6200',
   '4. close': '42.5500',
   '5. volume': '22174963'},
  '2021-01-27': {'1. open': '40.7400',
   '2. high': '41.6500',
   '3. low': '40.3120',
   '4. close': '40.9100',
   '5. volume': '15279986'},
  '2021-01-26': {'1. open': '40.8000',
   '2. high': '41.3900',
   '3. low': '40.5600',
   '4. close': '41.2500',
   '5. volume': '13388598'},
  '2021-01-25': {'1. open': '41.5400',
   '2. high': '41.7300',
   '3. low': '39.9000',
   '4. close': '40.3800',
   '5. volume': '20281919'},
  '2021-01-22': {'1. open': '41.9500',
   '2. high': '42.2900',
   '3. low': '41.6100',
   '4. close': '42.1400',
   '5. volume': '13544971'},
  '2021-01-21': {'1. open': '43.8035',
   '2. high': '43.9800',
   '3. low': '41.7150',
   '4. close': '42.5900',
   '5. volume': '32185626'},
  '2021-01-20': {'1. open': '45.0400',
   '2. high': '45.6500',
   '3. low': '44.4100',
   '4. close': '45.1800',
   '5. volume': '11661304'},
  '2021-01-19': {'1. open': '44.6000',
   '2. high': '44.9000',
   '3. low': '43.7700',
   '4. close': '44.7500',
   '5. volume': '9706312'},
  '2021-01-15': {'1. open': '45.8500',
   '2. high': '45.9800',
   '3. low': '43.8800',
   '4. close': '43.8900',
   '5. volume': '13211536'},
  '2021-01-14': {'1. open': '45.3200',
   '2. high': '46.8000',
   '3. low': '45.3200',
   '4. close': '46.2900',
   '5. volume': '16310456'},
  '2021-01-13': {'1. open': '44.1700',
   '2. high': '44.6400',
   '3. low': '43.4400',
   '4. close': '44.4300',
   '5. volume': '11390177'},
  '2021-01-12': {'1. open': '42.8098',
   '2. high': '44.1700',
   '3. low': '42.4600',
   '4. close': '44.0800',
   '5. volume': '9028885'},
  '2021-01-11': {'1. open': '42.6700',
   '2. high': '43.2599',
   '3. low': '42.2500',
   '4. close': '42.7000',
   '5. volume': '8988803'},
  '2021-01-08': {'1. open': '43.5800',
   '2. high': '44.0000',
   '3. low': '43.0200',
   '4. close': '43.2900',
   '5. volume': '9215340'},
  '2021-01-07': {'1. open': '43.8035',
   '2. high': '44.8399',
   '3. low': '43.6100',
   '4. close': '43.6200',
   '5. volume': '9592931'},
  '2021-01-06': {'1. open': '43.6000',
   '2. high': '44.2800',
   '3. low': '42.8600',
   '4. close': '43.5400',
   '5. volume': '12318860'},
  '2021-01-05': {'1. open': '41.5800',
   '2. high': '43.6000',
   '3. low': '41.5000',
   '4. close': '43.4000',
   '5. volume': '12294450'},
  '2021-01-04': {'1. open': '43.6800',
   '2. high': '43.7000',
   '3. low': '41.4300',
   '4. close': '41.6300',
   '5. volume': '14710220'},
  '2020-12-31': {'1. open': '44.4100',
   '2. high': '44.5617',
   '3. low': '43.1100',
   '4. close': '43.2500',
   '5. volume': '12683975'},
  '2020-12-30': {'1. open': '43.6350',
   '2. high': '44.7600',
   '3. low': '43.4600',
   '4. close': '44.6500',
   '5. volume': '9473270'},
  '2020-12-29': {'1. open': '44.4500',
   '2. high': '44.6489',
   '3. low': '43.5500',
   '4. close': '43.7400',
   '5. volume': '9927674'},
  '2020-12-28': {'1. open': '44.0350',
   '2. high': '44.6250',
   '3. low': '43.7500',
   '4. close': '43.9200',
   '5. volume': '13493892'},
  '2020-12-24': {'1. open': '44.4000',
   '2. high': '44.4165',
   '3. low': '43.0100',
   '4. close': '43.2600',
   '5. volume': '7230607'},
  '2020-12-23': {'1. open': '43.1000',
   '2. high': '44.6900',
   '3. low': '43.0800',
   '4. close': '44.1100',
   '5. volume': '15284729'},
  '2020-12-22': {'1. open': '44.6500',
   '2. high': '44.7900',
   '3. low': '42.4300',
   '4. close': '42.9700',
   '5. volume': '16602731'},
  '2020-12-21': {'1. open': '43.3500',
   '2. high': '44.4200',
   '3. low': '42.6300',
   '4. close': '44.0550',
   '5. volume': '21879086'},
  '2020-12-18': {'1. open': '45.7500',
   '2. high': '45.9500',
   '3. low': '44.5600',
   '4. close': '44.7400',
   '5. volume': '16333232'},
  '2020-12-17': {'1. open': '46.3000',
   '2. high': '46.4000',
   '3. low': '45.4600',
   '4. close': '45.8800',
   '5. volume': '13785021'},
  '2020-12-16': {'1. open': '46.5000',
   '2. high': '46.9100',
   '3. low': '45.5500',
   '4. close': '46.0000',
   '5. volume': '17369545'},
  '2020-12-15': {'1. open': '47.1950',
   '2. high': '47.5600',
   '3. low': '45.8000',
   '4. close': '47.4600',
   '5. volume': '16836295'},
  '2020-12-14': {'1. open': '49.6040',
   '2. high': '49.6500',
   '3. low': '46.7000',
   '4. close': '46.7200',
   '5. volume': '15744995'},
  '2020-12-11': {'1. open': '49.1500',
   '2. high': '49.8900',
   '3. low': '47.6400',
   '4. close': '48.3600',
   '5. volume': '14770643'},
  '2020-12-10': {'1. open': '46.7400',
   '2. high': '49.7100',
   '3. low': '46.6000',
   '4. close': '49.6400',
   '5. volume': '19020500'},
  '2020-12-09': {'1. open': '49.8400',
   '2. high': '50.0899',
   '3. low': '46.7300',
   '4. close': '48.0200',
   '5. volume': '23325078'},
  '2020-12-08': {'1. open': '49.0200',
   '2. high': '50.4000',
   '3. low': '48.7201',
   '4. close': '49.0400',
   '5. volume': '17797906'},
  '2020-12-07': {'1. open': '49.2800',
   '2. high': '50.3544',
   '3. low': '48.7100',
   '4. close': '49.2000',
   '5. volume': '22364645'},
  '2020-12-04': {'1. open': '50.4900',
   '2. high': '51.3100',
   '3. low': '48.7700',
   '4. close': '49.2400',
   '5. volume': '26300629'},
  '2020-12-03': {'1. open': '47.6700',
   '2. high': '50.9700',
   '3. low': '47.6600',
   '4. close': '49.9100',
   '5. volume': '32545226'},
  '2020-12-02': {'1. open': '45.1000',
   '2. high': '46.7300',
   '3. low': '44.5200',
   '4. close': '46.7300',
   '5. volume': '17745667'},
  '2020-12-01': {'1. open': '45.8300',
   '2. high': '46.5698',
   '3. low': '45.2300',
   '4. close': '45.3200',
   '5. volume': '18644226'},
  '2020-11-30': {'1. open': '46.4650',
   '2. high': '46.5000',
   '3. low': '44.2000',
   '4. close': '45.0500',
   '5. volume': '23401474'},
  '2020-11-27': {'1. open': '46.2000',
   '2. high': '46.7600',
   '3. low': '45.1400',
   '4. close': '45.3000',
   '5. volume': '14103891'},
  '2020-11-25': {'1. open': '44.4900',
   '2. high': '45.9100',
   '3. low': '43.6500',
   '4. close': '45.6400',
   '5. volume': '24250768'},
  '2020-11-24': {'1. open': '42.7080',
   '2. high': '45.0000',
   '3. low': '42.4500',
   '4. close': '44.9600',
   '5. volume': '29403031'},
  '2020-11-23': {'1. open': '40.1750',
   '2. high': '41.1800',
   '3. low': '40.0480',
   '4. close': '40.9300',
   '5. volume': '21729997'},
  '2020-11-20': {'1. open': '40.7100',
   '2. high': '40.9700',
   '3. low': '39.6700',
   '4. close': '39.9000',
   '5. volume': '15604677'}}}

In [10]:
df = pd.DataFrame(req['Time Series (Daily)']).transpose()
df.head()

            1. open  2. high   3. low 4. close 5. volume
2021-04-16  56.4700  57.1500  55.7100  55.8700  10620386
2021-04-15  57.7900  57.8514  55.5700  56.1200  12123396
2021-04-14  57.4600  58.5200  56.5400  56.9200  12971146
2021-04-13  54.4060  56.8600  53.9000  56.6600  15349381
2021-04-12  57.5700  57.7100  55.2900  56.1600  18714698

In [11]:
df['Date']=pd.to_datetime(df.index)
df.head()

            1. open  2. high   3. low 4. close 5. volume       Date
2021-04-16  56.4700  57.1500  55.7100  55.8700  10620386 2021-04-16
2021-04-15  57.7900  57.8514  55.5700  56.1200  12123396 2021-04-15
2021-04-14  57.4600  58.5200  56.5400  56.9200  12971146 2021-04-14
2021-04-13  54.4060  56.8600  53.9000  56.6600  15349381 2021-04-13
2021-04-12  57.5700  57.7100  55.2900  56.1600  18714698 2021-04-12

In [8]:
import numpy as np
from bokeh.layouts import gridplot
from bokeh.plotting import figure, show, output_file

In [12]:
def datetime(x):
    return np.array(x, dtype=np.datetime64)

plt = figure(x_axis_type="datetime", title="Closing Prices")
plt.grid.grid_line_alpha= 0.5
plt.xaxis.axis_label = 'Date'
plt.yaxis.axis_label = 'Price'

plt.line(datetime(df['Date']), df['4. close'])
#p1.legend.location = "top_left"

show(plt)

In [16]:
pip install Flask-WTF

Collecting Flask-WTF
  Downloading https://files.pythonhosted.org/packages/36/a9/8c01171066bd7a524ee005d81bb4a8aa446ab178043a1ad6cb5dc8f0bd83/Flask_WTF-0.14.3-py2.py3-none-any.whl
Requirement already satisfied: itsdangerous in c:\users\uriel\anaconda3\lib\site-packages (from Flask-WTF) (1.1.0)
Collecting WTForms (from Flask-WTF)
  Downloading https://files.pythonhosted.org/packages/e0/31/614fc7dc7d76005b0acb8c0c8920d962b83d7422b4ba912886dfb63f86ff/WTForms-2.3.3-py2.py3-none-any.whl (169kB)
Requirement already satisfied: Flask in c:\users\uriel\anaconda3\lib\site-packages (from Flask-WTF) (1.1.0)
Requirement already satisfied: MarkupSafe in c:\users\uriel\anaconda3\lib\site-packages (from WTForms->Flask-WTF) (1.1.1)
Requirement already satisfied: Werkzeug>=0.15 in c:\users\uriel\anaconda3\lib\site-packages (from Flask->Flask-WTF) (0.15.4)
Requirement already satisfied: Jinja2>=2.10.1 in c:\users\uriel\anaconda3\lib\site-packages (from Flask->Flask-WTF) (2.10.1)
Requirement already satisfied: click>=5.1 in c:\users\uriel\anaconda3\lib\site-packages (from Flask->Flask-WTF) (7.1.2)
Installing collected packages: WTForms, Flask-WTF
Successfully installed Flask-WTF-0.14.3 WTForms-2.3.3
Note: you may need to restart the kernel to use updated packages.